### ISSUE TITLE
b3维度

### ISSUE THREAD

**Issue by Donaghys** [Jintao-Huang/efficientnet_pytorch#2]
您好，请问b3的实现是是不是与论文有出路呢？有点改动呢

**Comment by Jintao-Huang** [comment]
应该是没改动过的，这个是参数情况。请问具体哪个地方有出入？
https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_builder.py

**Comment by Donaghys** [comment]
我用您复现的这个网络进行了替换ResNet50，

我自己输入了一张图片（1，3，320，320），打印了每个阶段生成特征图的尺寸，观察卷积的尺寸，发现打印出来的尺寸依次是
torch.Size([1, 40, 160, 160])
torch.Size([1, 24, 160, 160])
torch.Size([1, 32, 80, 80])
torch.Size([1, 48, 40, 40])
torch.Size([1, 96, 20, 20])
torch.Size([1, 136, 20, 20])
torch.Size([1, 232, 10, 10])
torch.Size([1, 384, 10, 10])


有点跟网络的结构不太一样，  我再仔细看一遍网络~~~，感谢。
